# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x12\x08location\"\xe3\x03\n\x12WifiClientLocation\x12\x0e\n\x01x\x18\x01 \x01(\x01H\x00\x88\x01\x01\x12\x0e\n\x01y\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12\x18\n\x0b\x65rror_level\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x18\n\x0bsta_eth_mac\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x16\n\tlongitude\x18\x05 \x01(\x01H\x04\x88\x01\x01\x12\x15\n\x08latitude\x18\x06 \x01(\x01H\x05\x88\x01\x01\x12\x14\n\x07site_id\x18\x07 \x01(\tH\x06\x88\x01\x01\x12\x18\n\x0b\x62uilding_id\x18\x08 \x01(\tH\x07\x88\x01\x01\x12\x15\n\x08\x66loor_id\x18\t \x01(\tH\x08\x88\x01\x01\x12\x1b\n\x13reporting_ap_serial\x18\n \x03(\t\x12\x17\n\nassociated\x18\x0b \x01(\x08H\t\x88\x01\x01\x12\x18\n\x0b\x61ssoc_bssid\x18\x0c \x01(\tH\n\x88\x01\x01\x12\x16\n\tconnected\x18\r \x01(\x08H\x0b\x88\x01\x01\x42\x04\n\x02_xB\x04\n\x02_yB\x0e\n\x0c_error_levelB\x0e\n\x0c_sta_eth_macB\x0c\n\n_longitudeB\x0b\n\t_latitudeB\n\n\x08_site_idB\x0e\n\x0c_building_idB\x0b\n\t_floor_idB\r\n\x0b_associatedB\x0e\n\x0c_assoc_bssidB\x0c\n\n_connectedB-\n+com.hpe.gravity.apistreaming.proto.locationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n+com.hpe.gravity.apistreaming.proto.location'
  _WIFICLIENTLOCATION._serialized_start=29
  _WIFICLIENTLOCATION._serialized_end=512
# @@protoc_insertion_point(module_scope)
